# Generated by Django 5.0 on 2024-04-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_brand_product_orgin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='orgin',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
