<<<<<<< HEAD
# Generated by Django 5.0 on 2024-05-26 12:59
=======
# Generated by Django 4.2.11 on 2024-05-26 12:47
>>>>>>> 4f5fd1a46dd839d266110b0fc13636794b68cd55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/product'),
        ),
    ]
